version: "3"
services:
  db:
    image: mysql:8.0.23
    container_name: wgp-db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
  web:
    build: .
    image: wgp-web
    container_name: wgp-web
    command: >
      /app/wait-for-it.sh db:3306 -- /app/scripts/launch-app.sh
    environment:
      DB_PASS: root_password
      DB_HOST: db
    ports:
      - "3000:3000"
    links:
      - db
